In [29]:
import numpy as np

A = np.random.randint(1, 99, size = (2,8))
# print(x)
# print(type(x)) // <class 'numpy.ndarray'>

# A 벡터의 차원 정보 및 각 서브 벡터 크기를 출력하고, 벡터에 저장된 모든 값 출력
print(A.shape)
print(A.shape[0])
print(A.shape[1])
print(A)

print()
print("----------------------")
print()
# For 루프와 shape 문법을 사용하여 A 벡터 전체 원소들의 최대값과 서브 벡터 내의 최대값을 찾아서 출력
x = A[0][0]
y = A[1][0]

for i in range(A.shape[1]):
  if x < A[0][i]:
    x = A[0][i]

  if y < A[1][i]:
    y = A[1][i]

if(x < y):
  print("All Max: ", y)
else:
  print("All Max: ", x)

print("SubMax 0: ", x)
print("SubMax 1: ", y)

print()
print("----------------------")
print()
# 2차원 백터 A를 2x2x4의 크기으ㅢ 3차원 벡터 B로 변환. 그리고 B 벡터의 차원 정보를 출력하고, B 벡터의 저장된 모든 값을 출력
B = A.reshape(2,2,4)

print(B.shape)
print(B)

print()
print("----------------------")
print()
print()

# HW1_2
C = B.copy()

C[ : , : , 0:2] = B[ : , : , 2: ]
C[ : , : , 2: ] = B[ : , : , :2 ]
print(C)

(2, 8)
2
8
[[14 40 77  4  2  7 83 93]
 [96 93 59 26 34  4 95  2]]

----------------------

All Max:  96
SubMax 0:  93
SubMax 1:  96

----------------------

(2, 2, 4)
[[[14 40 77  4]
  [ 2  7 83 93]]

 [[96 93 59 26]
  [34  4 95  2]]]

----------------------


[[[77  4 14 40]
  [83 93  2  7]]

 [[59 26 96 93]
  [95  2 34  4]]]
